ibexa/behat

src/lib/Browser/Assert/CollectionAssert.php, src/lib/Browser/Assert/CollectionAssertInterface.php, src/lib/Browser/Assert/Debug/Interactive/CollectionAssert.php, tests/Browser/Element/Assert/CollectionAssertTest.php
Backport of https://github.com/ezsystems/BehatBundle/pull/274 to 4.0
=> Added containsElementsWithText assertion

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml, features/setup/multirepository/multirepository.feature
> JIRA: [IBX-2738](https://issues.ibexa.co/browse/IBX-2738)
I've added new test scenarios for adding, editing and removing attribute group in product catalog.
Related PR:
https://github.com/ibexa/product-catalog/pull/549
=> [Behat] IBX-2320 Added scenario for add Attribute group in product catalog

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
> JIRA: [IBX-2738](https://issues.ibexa.co/browse/IBX-2739)
I've added new test scenarios for adding, editing and removing attributes in product catalog.
Related PR:
https://github.com/ibexa/product-catalog/pull/590
=> [Behat] IBX-2739: Added test scenarios for attributes in product catalog

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
JIRA: https://issues.ibexa.co/browse/IBX-2740 
Related: https://github.com/ibexa/product-catalog/pull/552
=> [Behat] IBX-2740: Implemented tests for Product Types in product catalog

.github/workflows/browser-tests.yaml, .github/workflows/ci.yaml
The name of the default branch is `main`, not `master`.
=> [CI] Fixed running tests on main branch

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
> JIRA: [IBX-3048](https://issues.ibexa.co/browse/IBX-3048)
I've added new test scenarios for adding, publishing, archiving, copying, editing and removing catalogs in product catalog.
Related PRs:
https://github.com/ibexa/product-catalog/pull/706
https://github.com/ibexa/admin-ui/pull/517
=> [Behat] IBX-3048 Added tests for catalogs

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
JIRA: https://issues.ibexa.co/browse/IBX-2741
Related: https://github.com/ibexa/product-catalog/pull/775
=> [Behat] IBX-2741: Implemented tests for Products in product catalog

tests/lib/Browser/Filter/BrowserLogFilterTest.php, tests/lib/Core/Behat/ArgumentParserTest.php, tests/lib/Core/Behat/ExtendedTableNodeTest.php, tests/lib/Core/Configuration/ConfigurationEditorTest.php, tests/lib/Core/Configuration/LocationAwareConfigurationEditorTest.php, tests/lib/Core/Log/LogFileReaderTest.php
Same as https://github.com/ibexa/product-catalog/pull/780
=> Fixed codestyle

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
This PR adds path to product catalog setup.
JIRA: https://issues.ibexa.co/browse/IBX-3842 
Related:
https://github.com/ibexa/product-catalog/pull/808 
https://github.com/ibexa/admin-ui/pull/587
=> [Behat] IBX-3842: Extend test scenarios for Products

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
Follow-up to https://github.com/ibexa/behat/pull/46
=> [Behat] IBX-3842: Changed path to product catalog features

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
> JIRA: [IBX-3994](https://issues.ibexa.co/browse/IBX-3994)
I've added new test scenarios for adding, editing and deleting customer groups in product catalog.
Related PRs:
https://github.com/ibexa/product-catalog/pull/858
=> [Behat] IBX-3394: Added test scenarios for customer groups in product catalog

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml
JIRA: https://issues.ibexa.co/browse/IBX-4409
=> [Behat] IBX-4409: Implemented test scenarios for Currencies

src/lib/Browser/Page/LoginPage.php
Tested in:
https://github.com/ibexa/oss/pull/85
https://github.com/ibexa/commerce/pull/199
=> Expanded possible login button names to include Storefront

.github/workflows/browser-tests.yaml
Follow-up to https://github.com/ibexa/gh-workflows/pull/32
=> [CI] Removed project version

behat_ibexa_experience.yaml, behat_ibexa_headless.yaml
[IBX-5798](https://issues.ibexa.co/browse/IBX-5798)
=> IBX-5798: Ibexa Headless regression tests

behat_ibexa_commerce.yaml, behat_ibexa_experience.yaml, behat_ibexa_headless.yaml, behat_ibexa_oss.yaml
Contexts added to match the https://github.com/ibexa/admin-ui/pull/878
=> IBX-6330: Cover "My Drafts" Page, adding new contexts

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml, src/lib/API/ContentData/FieldTypeData/TextLineDataProvider.php, src/lib/API/ContentData/FieldTypeNameConverter.php, src/lib/API/Context/ContentTypeContext.php, src/lib/Browser/Element/BaseElement.php, src/lib/Browser/Element/Mapper/ElementAttributeMapper.php, tests/lib/Browser/Element/Mapper/ElementAttributeMapperTest.php, tests/lib/Browser/Element/Mapper/ElementTextMapperTest.php
Backport of https://github.com/ibexa/behat/pull/67 to 4.5
=> Add taxonomy test v45

behat_ibexa_commerce.yaml, behat_ibexa_content.yaml, behat_ibexa_experience.yaml, behat_ibexa_oss.yaml
[IBX6406](https://issues.ibexa.co/browse/IBX-6406)
context added to mach [#890](https://github.com/ibexa/admin-ui/pull/890)
Backport of #73
=> IBX-6406: Cover "My Drafts" Page, adding new contexts, backport

behat_ibexa_commerce.yaml
JIRA: https://issues.ibexa.co/browse/IBX-6335 
This PR adds config for shipping
=> IBX-6335: Implemented test scenarios to cover Shipping methods

src/lib/Browser/Element/Action/ActionInterface.php, src/lib/Browser/Element/Action/ChainAction.php, src/lib/Browser/Element/Action/Click.php, src/lib/Browser/Element/Action/MouseOver.php, src/lib/Browser/Element/Action/MouseOverAndClick.php, src/lib/Browser/Element/Action/Wait.php, src/lib/Browser/Element/Debug/Highlighting/Element.php, src/lib/Browser/Element/Debug/Interactive/Element.php, src/lib/Browser/Element/Element.php, src/lib/Browser/Element/ElementInterface.php
This PR adds small `Action` classes that can be chained.
This should make our life easier when it comes to the `MouseOverAndClick` action which became quite common in some places - and this is the main goal of this PR.
Example usage:
https://github.com/ibexa/admin-ui/pull/922
=> Added Actions

behat_ibexa_commerce.yaml, behat_ibexa_experience.yaml
This PR adds config for page builder setup feature.
Related PR: https://github.com/ibexa/page-builder/pull/240 & https://github.com/ibexa/fieldtype-page/pull/93
=> [Behat] IBX-2319: added config for page builder setup

.github/workflows/browser-tests.yaml, src/bundle/DependencyInjection/IbexaBehatExtension.php
This should hopefully help with https://issues.ibexa.co/browse/IBX-6743
You can see that the issue is not gone, but I think it makes it more stable (2 jobs out of 13 have failed).
Additional PR that should help: https://github.com/ibexa/admin-ui/pull/936
=> Increased success notification timeout

.github/workflows/ci.yaml, composer.json, phpstan-baseline.neon, phpstan.neon, src/lib/Browser/Component/Component.php, src/lib/Browser/Element/Debug/Interactive/RootElement.php
Lots of changes here, but they are mostly autogenerated 😉 
Commits:
1) Adds PHPStan that will be looking into our code to improve its quality 🕵️ 🐛 Also handles one issue that PHPStan was not able to handle
2) Adds all the existing issues to the baseline - the goal is to fix them slowly, over time. This file is autogenerated by PHPStan
3) Add a way of accesing Chrome DevTools driver from the Pages/Components - this is based on https://github.com/ibexa/visual-testing/pull/24
=> Added way of accesing the Chrome DevToolsDriver

src/bundle/Subscriber/StartScenarioSubscriber.php
JIRA: https://issues.ibexa.co/browse/IBX-6366
Example failure:
https://github.com/ibexa/commerce/actions/runs/6646552039/job/18060721847
```
In WebDriverException.php line 146:
[Facebook\WebDriver\Exception\UnknownErrorException]                                    
unknown error: failed to change window state to 'normal', current state is 'maximized'  
(Session info: chrome=110.0.5481.177)                                                 
Exception trace:
at /var/www/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:146
Facebook\WebDriver\Exception\WebDriverException::throwException() at /var/www/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:359
Facebook\WebDriver\Remote\HttpCommandExecutor->execute() at …
```
=> Added retrying mechanism to window resizing

src/bundle/Resources/config/services/known_issues.yaml, src/lib/Core/Log/Failure/KnownIssues/FailedLogin.php
This PR adds https://issues.ibexa.co/browse/IBX-4672 to the list of known issues
=> Added issue detection for IBX-4672

behat_ibexa_commerce.yaml, behat_ibexa_experience.yaml
Requires: https://github.com/ibexa/dashboard/pull/37
=> Added Dashboard suites

.github/workflows/ci.yaml, composer.json, phpstan-baseline.neon, src/lib/Core/Behat/ArgumentParser.php, tests/Browser/Element/Assert/CollectionAssertTest.php, tests/bundle/Form/RetryChoiceListFactoryTest.php, tests/lib/Browser/Element/Condition/ElementTransitionHasEndedConditionTest.php, tests/lib/Browser/Element/Mapper/ElementTextMapperTest.php
| :ticket: Issue | IBX-8279 |
In this PR:
1. Test matrix is streamlined to PHP 8.3
2. ibexa/code-style version is increased accordingly
3. Code style issues are addressed
4. Tests are updated to PHP 8.3.
=> IBX-8279: Updated test matrix configuration for 5.0

src/lib/Browser/Page/RedirectLoginPage.php
| :ticket: Issue | IBX-8140 |
Temporarily disabled faulty assertion in loginSuccessfully.
=> IBX-8140: Disabled faulty assertion in loginSuccessfully

src/lib/API/ContentData/FieldTypeData/ImageDataProvider.php
| :ticket: Issue | IBX-8534 |
Path is deprecated since ezPublish 5.0 (10 years.)
=> IBX-8534: Replaced deprecated path with inputUri

src/lib/Data/Templates/SiteFactory/pagelayout1.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout10.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout11.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout12.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout13.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout14.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout15.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout16.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout17.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout18.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout19.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout2.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout20.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout3.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout4.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout5.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout6.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout7.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout8.html.twig, src/lib/Data/Templates/SiteFactory/pagelayout9.html.twig
| :ticket: Issue | IBX-XXXXX |
- https://github.com/ibexa/site-factory/pull/111
This PR updates outdated pagelayout twigs with Ibexa syntax.
=> Updated site factory pagelayout twigs

.github/workflows/rector.yaml, composer.json, rector.php, src/bundle/Command/CreateExampleDataCommand.php, src/bundle/Command/CreateExampleDataManagerCommand.php, src/bundle/Command/CreateLanguageCommand.php, src/bundle/Command/TestSiteaccessCommand.php, src/lib/Core/Debug/Command/GoBackCommand.php, src/lib/Core/Debug/Command/RefreshPageCommand.php, src/lib/Core/Debug/Command/ShowHTMLCommand.php, src/lib/Core/Debug/Command/ShowURLCommand.php, src/lib/Core/Debug/Command/TakeScreenshotCommand.php
| :ticket: Issue | IBX-9627 |
Added Rector to GHA CI.
=> IBX-9627: [GHA][Rector] Added and configured Ibexa Rector for GHA CI

behat_ibexa_commerce.yaml, behat_ibexa_experience.yaml, behat_ibexa_headless.yaml
| :ticket: Issue | IBX-9315 |
- https://github.com/ibexa/connector-openai/pull/37
Added AI Assistant context & config.
=> Added AI Assistant config & context

composer.json, src/bundle/Cache/JsRoutingDirectoryCacheDirectoryCreator.php, tests/bundle/Form/Stub/UnstableChoiceListFactory.php
> [!CAUTION]
> # Merge together with other IBX-8471 Pull Requests
> - [x] Make sure TMP commit(s) are dropped before merging
| :ticket: Issue | IBX-8471 |
Upgrading Symfony dependencies to version 7 along with necessary 3rd party packages and codebase changes.
Key changes:
Sanity tests and/or regression builds.
=> IBX-8471: Upgraded codebase to Symfony 7

behat_ibexa_commerce.yaml
| :ticket: Issue | IBX-9859 |
- https://github.com/ibexa/discounts/pull/219
=> IBX-9859: Added discounts config

src/lib/QueryType/FoldersUnderMediaQueryType.php
| :ticket: Issue | N/A       |
- https://github.com/ibexa/core/pull/565
Ref. https://github.com/ibexa/fieldtype-matrix/actions/runs/15433746391/job/43436149882?pr=72#step:18:142
N/A
N/A
=> Added casting for locationId in FoldersUnderMediaQueryType

behat_ibexa_commerce.yaml, src/lib/Core/Behat/TableNodeExtension.php
| :ticket: Issue | [IBX-9862](https://issues.ibexa.co/browse/IBX-9862) |
- https://github.com/ibexa/storefront/pull/213
- https://github.com/ibexa/discounts/pull/240
Configuration added to make the tests visible in regression.
PHPStan is failing, but not because of my code. I think there's a PR here, but it's already merged to main. - https://github.com/ibexa/behat/pull/146
https://github.com/ibexa/commerce/actions/runs/15462691824/job/43527530479?pr=1313#step:18:31
=> IBX-9862: Add discounts storefront config
