ibexa/behat

- src/lib/Browser/Element/BaseElement.php
- src/lib/Browser/Element/Debug/Highlighting/Element.php
- src/lib/Browser/Element/Debug/Interactive/Element.php
- src/lib/Browser/Element/Element.php
- src/lib/Browser/Element/ElementInterface.php
Required by https://github.com/ibexa/workflow/pull/45
Added a way to scroll to the bottom of an Element.
Example usage:
```
$this->getHTMLPage()->find(<CSSLOCATOR>)->scrollToBottom();
```
Mainly used to work around the "go to the top" button that appears out of nowhere and covers the element we want to click on.
> Added a way of scrolling to the bottom of an element

- src/lib/API/ContentData/ContentDataProvider.php
Error in tests:
```
And there's draft "TestDraftDashboardEdit" on Dashboard list        # Ibexa\AdminUi\Behat\BrowserContext\DashboardContext::goingToDashboardISeeDraft()
Ibexa\Behat\Browser\Exception\TimeoutException: Next page in pagination was not reloaded in time. Current page is: 5, expected 6 in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:79
Stack trace:
#0 vendor/ibexa/admin-ui/src/lib/Behat/Component/Pagination.php(37): Ibexa\Behat\Browser\Element\BaseElement->waitUntil()
#1 vendor/ibexa/admin-ui/src/lib/Behat/Component/Table/Table.php(76): Ibexa\AdminUi\Behat\Component\Pagination->clickNextButton()
#2 vendor/ibexa/admin-ui/src/lib/Behat/Page/DashboardPage.php(51): Ibexa\AdminUi\Behat\Component\Table\Table->hasElement()
#3 …
```
> Removed generating Content Items with a random date

- src/lib/Browser/Element/RootElement.php
JIRA: https://issues.ibexa.co/browse/IBX-2803
> IBX-2803: Fix drag and drop after React update

- .github/workflows/browser-tests.yaml
- features/setup/multirepository/multirepository.feature
- src/lib/Core/Configuration/ConfigurationEditor.php
- src/lib/Core/Configuration/ConfigurationEditorInterface.php
- src/lib/Core/Configuration/LocationAwareConfigurationEditor.php
- src/lib/Core/Context/ConfigurationContext.php
- tests/lib/Core/Configuration/ConfigurationEditorTest.php
Follow-up to the changes from https://github.com/ibexa/behat/pull/19/files#diff-0dfc35e37a342600d9ae2f9aafb33a7f5950c30b75d45ecb489512d19910d9edR22-R23
Nightly build error:
https://github.com/ibexa/oss/actions/runs/2471372918
```
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 322:
!!                                                                                 
!!    Unrecognized option "product_catalog" under "ibexa.repositories.new_reposit  
!!    ory". Available options are "fields_groups", "options", "search", "storage"  
!!    .    
```
My proposed solution is to create the new repository config based on the existing `default` config - and then change what's needed there.
I've tested it locally and the resulting …
> [Multirepository] Base new repository config on existing one

- .github/workflows/browser-tests.yaml
Change inspired by https://github.com/ibexa/behat/actions/runs/2759256184.
Corresponding setting: https://github.com/ibexa/admin-ui/blob/main/.github/workflows/browser-tests.yaml#L19
> [Browser tests] Added 40 min timeout to Admin UI tests

- src/lib/Core/Log/Failure/KnownIssues/ContentTypeCreatedInTheBackground.php
- src/lib/Core/Log/Failure/KnownIssues/TextBlockHeaderSelection.php
Based on 
1) https://github.com/ibexa/experience/runs/8045075656?check_suite_focus=true
```
│  	[2022-08-26T22:19:13.337306+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Warning: Undefined array key "ezcontentquery"")." at /var/www/vendor/ibexa/admin-ui/src/bundle/Resources/views/themes/admin/content/location_view.html.twig line 31 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Warning: Undefined array key \"ezcontentquery\"\"). at /var/www/vendor/ibexa/admin-ui/src/bundle/Resources/views/themes/admin/content/location_view.html.twig:31)\n[previous exception] [object] (ErrorException(code: 0): Warning: Undefined array …
```
> Adjusted known issues detection to v4

- composer.json
Right now our tests are failing when using fastest, because it's not compatible with doctrine/collections:^2.0
See: https://github.com/liuggio/fastest/pull/187#issuecomment-1451647396
This is a temporary requirement that will be removed once a release of liuggio/fastest supporting doctrine/collections v2 is available.
> [Composer] Limited doctrine/collections to ^1.8

- .github/workflows/browser-tests.yaml
- composer.json
Follow-up to https://github.com/ibexa/behat/pull/58 , which should not be needed after the latest fastest release:
https://github.com/liuggio/fastest/releases/tag/v1.11.0
I've also decided to run one of the test suites on PHP 8.1, so that we cover greater range of available dependencies in PR builds in this repository.
> [Composer] Removed doctrine/collections dependency

- behat_ibexa_oss.yaml
- composer.json
- src/lib/Browser/FileUpload/FileUploadHelper.php
JIRA: https://issues.ibexa.co/browse/IBX-4460
All PRs:
https://github.com/ibexa/recipes-dev/pull/60
https://github.com/ibexa/docker/pull/11
https://github.com/ibexa/version-comparison/pull/52
https://github.com/ibexa/admin-ui/pull/726
https://github.com/ibexa/behat/pull/59
Tested in https://github.com/ibexa/commerce/pull/227
Selenium has stopped publishing new images for the Selenum 3 version:
https://hub.docker.com/r/selenium/standalone-chrome-debug/tags
The latest release is from 2021-09-21, meaning we are using a browser that is slowly becoming outdated - and because new Selenium 3 Docker images are no longer published we need to move away from Selenium 3 and upgrade.
1) Chrome driver for Mink
Repository: https://gitlab.com/behat-chrome/chrome-mink-driver
It promises great results:
> …
> Selenium upgrade

- src/lib/Browser/Locator/CSSLocator.php
- src/lib/Browser/Locator/Validator/CssLocatorValidator.php
- tests/Browser/Locator/Validator/CssLocatorValidatorTest.php
- tests/lib/Core/Behat/ExtendedTableNodeTest.php
JIRA: https://issues.ibexa.co/browse/IBX-6230
This PR makes sure that it's not possible to use selectors that are not fully supported by the Symfony CssSelector component.
See: https://symfony.com/doc/current/components/css_selector.html#limitations-of-the-cssselector-component
```
Pseudo-classes are partially supported:
Not supported: *:first-of-type, *:last-of-type, *:nth-of-type and *:nth-last-of-type (all these work with an element name (e.g. li:first-of-type) but not with the * selector).
```
After this PR is merged it will be impossible to use a selector that is not supported - currently they can be used, but they are incorrectly translated into XPath and result in hard to debug issues.
Error:
Status:
> IBX-6230: Added validation of CSS selectors

- src/lib/Core/Log/TestLogProvider.php
This PR brings back support for accessing browser logs in PR logs (I had to adapt the solution to Selenium 4).
Tested in:
https://github.com/ibexa/behat/actions/runs/6311453842/job/17135473909?pr=81
```
│  JS Console errors:
│  	http://web/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)
```
> Browser log support

- composer.json
- src/bundle/Resources/views/tests/login_data.html.twig
- src/lib/Browser/Context/AuthenticationContext.php
- src/lib/Browser/Page/RedirectLoginPage.php
JIRA: https://issues.ibexa.co/browse/IBX-4672
This PR takes advantage of the Lock component (https://symfony.com/doc/current/components/lock.html#flockstore) to make sure only one test  (during parallel execution) is logging in at the same time - this should get rid of this kind of errors we were getting on CI recently.
I've also improved the post-login check, so that we can be sure that the login flow has completed.
Regression PR: https://github.com/ibexa/commerce/pull/394
> Added locking mechanism to Admin user login

- src/bundle/Resources/config/routing.yaml
- src/lib/Browser/Page/RedirectLoginPage.php
CI failure:
https://github.com/ibexa/experience/actions/runs/6318653184/job/17158104135
For Map\Host the redirect to our custom page is not working - Dashboard is displayed instead.
The responsible code is here:
https://github.com/ibexa/admin-ui/blob/main/src/lib/Security/Authentication/RedirectToDashboardListener.php#L55-L64
I've talked with @ViniTou and we won't be changing this logic for now, so I'm adding a workaround - nesting this path is enough to make it work.
Passing regression build: https://github.com/ibexa/experience/actions/runs/6318653184/job/17158104135
> Nested UnauthenticatedLoginRedirect route

- composer.json
- phpstan-baseline.neon
- src/bundle/Form/RetryChoiceListFactory.php
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/services/form.yaml
- tests/bundle/Form/RetryChoiceListFactoryTest.php
- tests/bundle/Form/Stub/UnstableChoiceListFactory.php
JIRA: https://issues.ibexa.co/browse/IBX-3075
Regression:
https://github.com/ibexa/experience/pull/253
https://github.com/ibexa/commerce/pull/428
1) AdminUI is using a choice loader to load the Content Types ([Type definition](https://github.com/ibexa/admin-ui/blob/main/src/lib/Form/Type/Content/Draft/ContentCreateType.php#L96), [Choice loader](https://github.com/ibexa/admin-ui/blob/main/src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php))
2) Symfony decorates it with [LazyChoiceList](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/ChoiceList/LazyChoiceList.php):
[It happens here](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L67) and means that the ChoiceLoader needs …
> Introduced RetryChoiceListFactory to deal with parallelism issues

- features/personas/change_password.feature
- features/personas/subtree_editor.feature
- phpstan-baseline.neon
- src/lib/API/Context/UserContext.php
Together with https://github.com/ibexa/dashboard/pull/44
We need to let these users acces the new Dashboard - this Role is available only in the Experience and Commerce editions.
I tried adding it in the Dashboard package, but it feels like a chore - because the AdminUI, Page Builder testa are failing and we would have to amend them as well.
This conditional assignment should be easier to maintain.
Regression:
https://github.com/ibexa/commerce/pull/482
> Added conditional Role assign to Dashboard role

- .github/workflows/browser-tests.yaml
- src/bundle/DependencyInjection/IbexaBehatExtension.php
Reverts https://github.com/ibexa/behat/pull/98 - it's no longer needed after the fix in https://github.com/ibexa/dashboard/pull/53
> Revert "[Workaround] Increased number of displayed Drafts as a workaround for Pagination issue (#98)"

- src/lib/API/Context/ContentTypeContext.php
- src/lib/Browser/Context/ContentPreviewContext.php
JIRA: https://issues.ibexa.co/browse/IBX-7409
Adjusted behat step description to be consistent with rest of DXP.
CI build - https://github.com/ibexa/commerce/actions/runs/7489083406/
> [Behat] IBX-7409: Adjusted behat step

- phpstan-baseline.neon
- src/lib/API/Context/LimitationParser/ContentTypeLimitationParser.php
- src/lib/Core/Debug/Shell/Shell.php
I made small changes to make PHPStan green, because it was failing.
The only real change here is the `in_array` -> `array_key_exists` change - the current code was wrong, we should be looking for the array keys, not array values.
> Fixed Content Type Limitation

- features/personas/add_location.feature
Follow-up to https://github.com/ibexa/workflow/pull/93
To avoid issues with the lack of taxonomy permissions I'm speciyfing a narrower set of permissions:
1) Only Content Types article and folder are allowed
I should also add Landing Page here, but this fails on lower editions (where the Landing Page CT doesn't exist).
To workaround that I'm using the Location limitation - this will make it possible to read the root location (which is a landing page) without using the landing page identifier.
Regression: https://github.com/ibexa/commerce/pull/635
> [Behat] Restricted content/read policy for the AddLocation user

- phpstan-baseline.neon
- phpstan.neon
- src/lib/Browser/Assert/CollectionAssertInterface.php
- src/lib/Browser/Component/Component.php
- src/lib/Browser/Element/BaseElement.php
- src/lib/Browser/Element/BaseElementInterface.php
- src/lib/Browser/Element/Element.php
- src/lib/Browser/Element/ElementCollection.php
- src/lib/Browser/Element/ElementCollectionInterface.php
- src/lib/Browser/Element/Mapper/MapperInterface.php
- src/lib/Browser/Element/RootElement.php
- src/lib/Browser/Locator/BaseLocator.php
- src/lib/Browser/Page/LoginPage.php
- src/lib/Browser/Page/Preview/FolderPreview.php
This PR makes it possible to invoke the `find` and `findAll` methods directly in Pages and Components - without calling `getHTMLPage` first.
It's a small thing, but should make our tests more readable and quicker to write.
I've also did small refactoring with PHPStan (I didn't want to introduce new issues into the baseline).
Regression: https://github.com/ibexa/commerce/pull/530
> Added helper find and findAll methods

- .github/workflows/browser-tests.yaml
- features/setup/multirepository/multirepository.feature
- features/setup/multirepository/multirepository_elastic.feature
- features/setup/multirepository/multirepository_solr.feature
- src/lib/API/Facade/UserFacade.php
**JIRA**: [IBX-6507](https://issues.ibexa.co/browse/IBX-6507)
Two things are covered:
1. On Solr newly created user group is not found on first attempt when creating user:
```
And I create a user group "SubtreeEditorsGroup"                                                           
And I create a user "SubtreeEditor" with last name "Subtree Editor" in group "SubtreeEditorsGroup"      
Ibexa\Core\Base\Exceptions\NotFoundException: Could not find 'User Group' with identifier 'SubtreeEditorsGroup' in vendor/ibexa/behat/src/lib/API/Facade/UserFacade.php:149
```
(e.g. https://github.com/ibexa/content/actions/runs/7300506772/job/19896363930?pr=106)
Loading User Group in User Facade is now retried few times every 0.5 second - https://github.com/ibexa/behat/pull/108/commits/2e606f0fa30fcf498e4e635 …
> IBX-6507: Adjustments for Solr and Elastic search engines

- src/bundle/Command/CreateExampleDataCommand.php
- src/bundle/Command/CreateExampleDataManagerCommand.php
- src/bundle/Command/CreateLanguageCommand.php
- src/bundle/Command/TestSiteaccessCommand.php
> IBX-8224: Dropped BackwardCompatibilityCommand interface

- .github/workflows/browser-tests.yaml
- features/personas/add_location.feature
- features/personas/subtree_editor.feature
- phpstan-baseline.neon
- src/bundle/Cache/JsRoutingDirectoryCacheDirectoryCreator.php
- src/bundle/Command/CreateExampleDataCommand.php
- src/bundle/Command/CreateExampleDataManagerCommand.php
- src/bundle/Command/CreateLanguageCommand.php
- src/bundle/Command/TestSiteaccessCommand.php
- src/bundle/Subscriber/EndScenarioSubscriber.php
- src/bundle/Subscriber/StartScenarioSubscriber.php
- src/lib/Core/Debug/Command/GoBackCommand.php
- src/lib/Core/Debug/Command/RefreshPageCommand.php
- src/lib/Core/Debug/Command/ShowHTMLCommand.php
- src/lib/Core/Debug/Command/ShowURLCommand.php
- src/lib/Core/Debug/Command/TakeScreenshotCommand.php
- src/lib/Subscriber/CreateContentDraft.php
- src/lib/Subscriber/EditContent.php
- src/lib/Subscriber/InitialStage.php
- src/lib/Subscriber/PublishDraft.php
- src/lib/Subscriber/PublishInTheFuture.php
- src/lib/Subscriber/Review.php
| :ticket: Issue | IBX-8138 |
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
> IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

- .github/workflows/browser-tests.yaml
- behat_ibexa_commerce.yaml
- behat_ibexa_experience.yaml
- behat_ibexa_headless.yaml
- behat_ibexa_oss.yaml
> [Behat] IBX-8638: As a QA I want to add behat coverage to user profile

- .github/workflows/browser-tests.yaml
| :ticket: Issue | IBX-8636 |
This PR adds new tag to admin ui job to exclude user profile test. In ibexa/behat repo we run admin-ui job on oss edition, Editor CT is enabled from headless edition, what causes a fail https://github.com/ibexa/behat/actions/runs/10279575369/job/28445202414
To use condition like `--tags='~@broken&&~@IbexaDXP'` we must use `--mode=standard` which consequently makes it impossible to use job-count (only in this job).
> [Behat] IBX-8636: Added new tag to admin-ui job

- composer.json
| :ticket: Issue | IBX-XXXXX |
This PR fixes CI failures such like https://github.com/ibexa/product-catalog-date-time-attribute/actions/runs/11832540541. It seems that 1.3.2 is the maximum version on which our current tests are green.
To be noted - this should be a **temporary** fix, and our friend-of-behat dependency should be resolved.
CI build: https://github.com/ibexa/commerce/pull/1115
> Fix for minkphpwebdriver 

- README.md
- behat_ibexa_oss.yaml
- composer.json
- phpstan-baseline.neon
- src/bundle/Form/RetryChoiceListFactory.php
- src/lib/Core/Debug/Matcher/ObjectFunctionCallChainMatcher.php
- src/lib/Core/Debug/Matcher/ThisObjectMethodsMatcher.php
- src/lib/Core/Debug/Shell/Shell.php
- tests/bundle/Form/RetryChoiceListFactoryTest.php
- tests/bundle/Form/Stub/UnstableChoiceListFactory.php
> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [x] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470 |
> [!WARNING]
> This is not ready, we need to resolve `bex/behat-screenshot` upgrade to SF 6
- https://github.com/ibexa/core/pull/447
- https://github.com/ibexa/doctrine-schema/pull/27
This PR bumps Symfony to v6 with necessary codebase upgrades.
Key changes:
Up to QA to decide.
No documentation required.
> IBX-8470: Upgraded codebase to Symfony 6

- phpstan-baseline.neon
- src/lib/Core/Log/Failure/TestFailureData.php
| :ticket: Issue | n/a |
|----------------|-----|
Seems there were some changes either to PHPStan or 3rd party Behat packages that started to cause CI to fail (within 3 months since the last successful run).
`\Behat\Behat\EventDispatcher\Event\BeforeScenarioTested::getScenario` returns an instance of `\Behat\Gherkin\Node\ScenarioLikeInterface` while `hasTag` that we try to call is defined on `\Behat\Gherkin\Node\TaggedNodeInterface`
If the subscriber is indeed executed and doesn't cause a fatal error, then it's just 3rd party bug related to type-hinting.
It's also possible that maybe we should retrieve the information we want using different API, but in that case Behat API would seem rather counter-intuitive IMO. It would require more investigation.
Added to baseline. …
> [4.6] Fixed issues found by PHPStan

- phpstan-baseline.neon
- src/lib/Browser/Element/BaseElement.php
- src/lib/Browser/Page/RedirectLoginPage.php
- tests/lib/Browser/Element/ElementTest.php
| :ticket: Issue | IBX-9217 |
- https://github.com/ibexa/recipes-dev/pull/156
This PR changes two things:
1. Increases the default timeout to 3 seconds. Also a unit test is adjusted to match the change.
There is a performance drop visible compared to v110. It affects different places e.g. Content Tree, Search, saving forms after creating/editing, previewing content.
`Content Tree`
https://github.com/ibexa/commerce/actions/runs/13260773669/job/37016681623#step:18:120
https://res.cloudinary.com/ezplatformtravis/image/upload/v1739271136/screenshots/67ab2be0b5609332224433-vendor_ibexa_admin-ui_features_standard_fields_media_feature_75_hsu9hk.png
https://github.com/ibexa/commerce/actions/runs/13260773669/job/37016683608#step:18:386 …
> IBX-9217: SELENIUM_IMAGE update to version 124.0-20250202

- src/bundle/DependencyInjection/IbexaBehatExtension.php
| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
* [symfony/http-kernel] Replaced usage of internal Symfony\Component\HttpKernel\DependencyInjection\Extension class
```
Sanities.
N/A
> IBX-9968: Resolved Symfony 7.x deprecations

- features/setup/multirepository/multirepository.feature
| :ticket: Issue | [IBX-10534](https://issues.ibexa.co/browse/IBX-10534) |
I have reproduced this issue locally and found the piece of configuration responsible for causing early initialization of database connection.
I am using a following configuration for Doctrine DBAL:
```yaml
doctrine: 
dbal: 
default_connection: default
connections: 
default: 
url: 'mysql://INVALID:INVALID@127.0.0.1/INVALID'
#server_version: '16'
use_savepoints: true
second_connection: 
url: '%env(resolve:DATABASE_URL)%'
#server_version: '16'
use_savepoints: true
```
Note, that use_savepoints: true is added by Symfony recipe. This is the source of the issue, because as part of configuring itself, Doctrine will call Doctrine\DBAL\Connection::setNestTransactionsWithSavepoints method, …
> IBX-10534: Prevent early database connection initialization
